# Set variables
PYTHON = python3
SCRIPT = bsgs_solver.py

# Default target
all: solve_puzzle

# Target to run the Python script
solve_puzzle:
	$(PYTHON) $(SCRIPT)

# Clean up any .pyc files generated by Python
clean:
	rm -rf __pycache__
